### ISSUE TITLE
File extensions settings precedence

### ISSUE THREAD

**Issue by rickmed** [formulahendry/vscode-code-runner#15] opened 2016-08-25 18:43 UTC
In my settings:

```
"code-runner.executorMapByFileExtension": {
    "*.js": "node",
    ".es": "npm run babel-node",
    ".ts": "npm run ts-node"
  },

  // Set the executor of each language.
  "code-runner.executorMap": {
    "sup": "npm run sup",
    "sup-babel": "npm run sup-babel",
    "javascript": "node",
    "php": "php",
    "python": "python",
    "perl": "perl",
    "ruby": "ruby",
    "go": "go run",
    "lua": "lua",
    "groovy": "groovy",
    "powershell": "powershell -ExecutionPolicy ByPass -File",
    "bat": "",
    "shellscript": "bash",
    "fsharp": "fsi",
    "csharp": "scriptcs",
    "vbscript": "cscript //Nologo"
  },
```

When I run a .es file, it runs node instead of npm run babel-node.
Note: no difference if setting "*.es" or ".es"

**Comment by formulahendry** [comment] 2016-08-26 11:31
Hi @rickmed , executorMap is prior to executorMapByFileExtension, it is by design. 
Per your requirement, I suggest you remove `"javascript": "node"` entry in executorMap and config executorMapByFileExtension like below (* is not recognised):
```json
"code-runner.executorMapByFileExtension": {
    ".js": "node",
    ".es": "npm run babel-node",
    ".ts": "npm run ts-node"
  },

**Comment by rickmed** [comment] 2016-08-26 15:32
@formulahendry I removed with but it is still running with node.

**Comment by formulahendry** [comment] 2016-08-26 16:05
Could you please share the screenshot?

**Comment by rickmed** [comment] 2016-08-26 17:23
![image](https://cloud.githubusercontent.com/assets/7104786/18014209/d33f0a64-6b8f-11e6-83c5-995c3f5b9fe2.png)

**Comment by formulahendry** [comment] 2016-08-27 01:24
Hi @rickmed , is it Workspace Settings or User Settings in your VS Code? Workspace Settings is prior to User Settings. Just want to confirm with you.

**Comment by rickmed** [comment] 2016-08-27 03:56
Is user settings but I have nothing in workspace settings

**Comment by formulahendry** [comment] 2016-08-27 03:59
Have you set the `code-runner.defaultLanguage`?

**Comment by rickmed** [comment] 2016-08-27 04:16
nope.

```
  // Set the default language to run.
  "code-runner.defaultLanguage": "",
```

**Comment by formulahendry** [comment] 2016-08-27 04:30
Could you please try below seetings?
```json
"code-runner.executorMapByFileExtension": {
    ".js": "echo .js & node",
    ".es": "echo .es & npm run babel-node",
    ".ts": "echo .ts & npm run ts-node"
  },

**Comment by rickmed** [comment] 2016-08-27 15:57
I get the same output -tried in user and workspace settings.

**Comment by formulahendry** [comment] 2016-08-28 04:12
Could you please try the below extension with debug info in output, and show me the output it prints.
[code-runner-0.2.2.zip](https://github.com/formulahendry/vscode-code-runner/files/440979/code-runner-0.2.2.zip)
(unzip it and use VS Code to open the vsix, the extension will be installed.)

**Comment by rickmed** [comment] 2016-08-28 15:35
```
[Debug] executorMap: javascript:node
[Debug] executorMap: php:php
[Debug] executorMap: python:python
[Debug] executorMap: perl:perl
[Debug] executorMap: ruby:ruby
[Debug] executorMap: go:go run
[Debug] executorMap: lua:lua
[Debug] executorMap: groovy:groovy
[Debug] executorMap: powershell:powershell -ExecutionPolicy ByPass -File
[Debug] executorMap: bat:
[Debug] executorMap: shellscript:bash
[Debug] executorMap: fsharp:fsi
[Debug] executorMap: csharp:scriptcs
[Debug] executorMap: vbscript:cscript //Nologo
[Debug] executorMap: sup:npm run sup
[Debug] executorMap: sup-babel:npm run sup-babel
[Debug] languageId: javascript
[Debug][Result] executorMap as languageId: javascript
[Running] node "c:\Users\rickm\Documents\Google Drive\Side-projects\Programming\NodeJS\playground-js\play.es"
true

[Done] exited with code=0 in 0.626 seconds
```

**Comment by formulahendry** [comment] 2016-08-29 11:24
Oh! Not sure whether it is VS Code bug to read config. It falls back to read `javascript` entry in default config. For quick turnaround, you coulde add `"javascript": null` in `code-runner.executorMap` instead of removing it.

**Comment by formulahendry** [comment] 2016-08-29 11:44
Submit an [issue](https://github.com/Microsoft/vscode/issues/11097) to VS Code

**Comment by rickmed** [comment] 2016-08-29 13:44
@formulahendry "javscript": null works! thanks!

**Comment by formulahendry** [comment] 2016-08-29 13:53
Great. :smile:

**Closed by formulahendry** 2016-08-29 13:53 UTC
Labels: external
