### ISSUE TITLE
Not able to run Swift

### ISSUE THREAD

**Issue by kareemamrr1203** [formulahendry/vscode-code-runner#263] opened 2018-02-27 19:12 UTC
I'm getting the below error when trying to run some swift code.
`[Running] swift "c:\Users\Kareem\Desktop\test.swift"
'swift' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by MzIy05** [comment] 2018-02-28 19:59
swift is compiled with Xcode and Xcode only works with Mac OS X, you can use an online compiling service with VB code or get  Mac OS X (through Virtual box or apple based system)

If you somehow managed to make swift run under windows the problem is your system variable path.

**Comment by formulahendry** [comment] 2018-03-04 08:16
Thanks @MzIy05 for the detailed explanation! Closing this issue.

**Closed by formulahendry** 2018-03-04 08:16 UTC
Labels: question

**Comment by Mashiro3131** [comment] 2022-10-25 10:56
This work now for me but now I have a new error: <unknown>:0: error: could not load the swift standard library.
Any idea how to solve this?
