### ISSUE TITLE
Output in C++ not working correctly

### ISSUE THREAD

**Issue by prep2** [formulahendry/vscode-code-runner#245] opened 2018-01-23 16:38 UTC
![2018-01-23 1](https://user-images.githubusercontent.com/8042703/35287844-efc5868e-0028-11e8-85a8-d690dbffea99.png)
On the right is Visual Studio 2017 which outputs my code correctly however VS Code using code runner does not. Using C++ with minGW 7.2.0 on VS Code.

These are the settings I have for Code Runner: 
 "code-runner.runInTerminal": true,
 "terminal.explorerKind": "integrated",
 "terminal.integrated.shell.windows":  "C:\\WINDOWS\\System32\\cmd.exe",

I have to use integrated terminal because I have to input.

**Comment by formulahendry** [comment] 2018-01-27 11:19
So the issue is that the output is not showing the full result?

**Comment by prep2** [comment] 2018-01-28 02:32
Yes, exactly that. Compiling through command prompt with MinGW and running the exe generated works fine. It seems like its just VS Code and Code Runner that don't generate the proper output.

**Comment by formulahendry** [comment] 2018-01-28 06:34
Do you use the same command to compile with MinGW?

**Comment by prep2** [comment] 2018-01-29 21:19
Not sure what you mean by that but when I use the built in terminal to build and run my code, I am getting the same issue so it seems to be VS Code and not Code Runner.

**Comment by formulahendry** [comment] 2018-01-30 01:30
Got it. So it is the issue of VS Code's integrated terminal. Close it as external issue. You could open an issue to https://github.com/microsoft/vscode/issues

**Closed by formulahendry** 2018-01-30 01:30 UTC
Labels: external
