### ISSUE TITLE
Python (Pandas) - Running code requires restart of VCS

### ISSUE THREAD

**Issue by Eventyret** [formulahendry/vscode-code-runner#129] opened 2017-06-19 16:22 UTC
So i came across this bug by writing a python code,

Requirements to make the bug,
Python, Pandas

1) Write any code that requires Pandas and try execute.
 - First time it might work, try rerun the code and you will get an error
`ImportError: No module named pandas`
2) Restart VCS run the code
- this will then work again.

Running the code directly from terminal in VCS with python test.py will not cause the bug.
If requesting more info or test code let me know.

**Comment by formulahendry** [comment] 2017-06-20 12:32
Could you show me the screenshot of the output?

**Comment by Eventyret** [comment] 2017-06-20 12:43
1) Executed both files one by using run code. You see the error, Then without closing or doing anything executing in cmd. You can see the code will work.
![1](https://user-images.githubusercontent.com/977232/27333590-4aa49d26-55be-11e7-8889-db94822bf815.PNG)
Restarted so only closed and reopen VCS. the "run code" and it works again. As you can see in picture 2
![2](https://user-images.githubusercontent.com/977232/27333591-4ac0877a-55be-11e7-89a5-25bb23677152.PNG)

**Comment by formulahendry** [comment] 2017-06-20 13:00
Could you try to go to `File` > `Preferences` -> `Settings` to add setting as below:
``` json
{
    "code-runner.runInTerminal": true
}
```
Then run it agian

**Comment by Eventyret** [comment] 2017-06-20 15:17
Great that works perfectly. Could you explain a bit what was the issue ?
Thanks again though.

**Comment by formulahendry** [comment] 2017-06-21 05:38
Good to know! Then closing this issue.
But I have no idea about the root cause. By default, the code will be run through Node child_process API. With `"code-runner.runInTerminal": true`, code will be run in Integrated Terminal of VS Code.

**Closed by formulahendry** 2017-06-21 05:38 UTC
Labels: need more info
