### ISSUE TITLE
code-runner not working

### ISSUE THREAD

**Issue by linhtto** [formulahendry/vscode-code-runner#351] opened 2018-08-28 06:33 UTC
I just installed VSCode recently (v1.26.1) on MacOS 10.13.6 and added code-runner. I tried it on a Python file and nothing happened upon executing "Run Code", either with anything selected or not. I then tried to choose Run Custom Command (the default one) and got this notification:

> Running the contributed command:'code-runner.runCustomCommand' failed.

The Output window is completely empty. 

I've tried to uninstall and reinstall, and also restart my computer.

**Comment by marcdahan** [comment] 2018-08-28 14:06
idem for me, but in my case a popup show : "command 'code-runner.customCommand' not found"  when using the keybinding : 

C:\Users\xxx\AppData\Roaming\Code\User\keybindings.json
    { 
    	"key": "ctrl+s",                    
    	"command": "code-runner.customCommand",
        "when": "editorTextFocus && editorLangId == 'scss'"
    }
and in : C:\Users\xxx\AppData\Roaming\Code\User\settings.json , I added : 
"code-runner.customCommand": "echo Marc"

but it's working using ctrl+shift +p "run custom command"

**Comment by linhtto** [comment] 2018-08-28 17:08
For me it doesn't work at all. If I try to run Python, for example, nothing happens and the OUTPUT window is empty. I tried to run the custom command in both ways, using the default keybinding ctrl + option + K and the Command Palette, I get the same popup notification. The difference is that the symbol on the notification is a red cross error sign if I run with the Command Palette, and a yellow warning sign if I run with the shortcut.

I already tried to disable all other extensions except this one to see if it makes a difference, but it doesn't. Basically I've never been able to get Code Runner to work at all.

**Comment by formulahendry** [comment] 2018-08-29 02:50
@linhtto Please delete the `C:\Users\***\.vscode\extensions\formulahendry.code-runner-***` folder and install extension again.

@marcdahan You need to use `code-runner.runCustomCommand`

**Comment by linhtto** [comment] 2018-08-29 03:00
@formulahendry , I use Mac, so the folder is in ~/.vscode. I deleted and reinstalled. But the same thing happens, I can't run anything. It doesn't matter if I turn on or off runInTerminal either.

**Comment by formulahendry** [comment] 2018-08-29 03:01
How about `Run Code` command?

**Comment by linhtto** [comment] 2018-08-29 03:03
It doesn't do anything at all. There's no notification, but the
Terminal/Output are just empty and there's no sign of anything running.

**Comment by formulahendry** [comment] 2018-08-29 03:09
Could you try VS Code Insider?

**Comment by linhtto** [comment] 2018-08-29 03:42
I just installed a fresh VS Code Insider and then Code Runner. And with this it works. I'm very confused about this.

```
[Running] echo Hello
Hello

[Done] exited with code=0 in 0.011 seconds
```

**Comment by linhtto** [comment] 2018-08-29 04:17
I reinstalled all my other packages (not too many and mostly standard ones), and it still works with VS Code Insider, but not VS Code the latest version 1.26.1 on MacOS 10.13.6.

**Comment by formulahendry** [comment] 2018-08-29 04:42
It may be the issue of VS Code, not this extension. So closing it.

**Closed by formulahendry** 2018-08-29 04:42 UTC
Labels: question

**Comment by linhtto** [comment] 2018-08-29 05:45
I think I figured it out so I'll just document here in case it happens to
others.

Previously I installed some small extensions to run specific programs
before I stumbled upon code runner which is much more comprehensive. I set
the same key binding for them since I want to run everything with the same
command. I uninstalled the other extensions but somehow code runner still
didn't work. I just realized those extensions still lived in
~/.vscode/extensions even though vscode itself didn't list them anymore.
Removing these obsolete folders did the trick. Code runner now works on the
stable vscode release as well.

**Comment by falconhurst** [comment] 2019-09-08 23:13
Turns out I had a similar issue:
Microsoft One Note uses ctrl+alt+n, so if you have that open Code-runner won't go

**Comment by glowdan** [comment] 2020-04-27 06:51
I encountered the same problem.
But just empty the ~/.vscode folder do not help me.
At last, I realize that may be the cause of the cache. So I cleaned the folder of "$HOME/Library/Application\ Support/Code"

Yeah the code runner is working again.

**Comment by odmoralesb** [comment] 2020-08-13 00:57
I updated VS and solved it

**Comment by jaynj908** [comment] 2020-11-04 03:25
I went to accounts/user(GITHUB) -Manage Trusted Extensions, typed code-runner in the command pallette and another instance of VS Code opened. I opened a Python file and tried  CTR+ALT+N and it worked? I was troubleshooting most of the day and just tried a random thing. Is there a hotkey for permissions that I might have hit?

**Comment by SerbanNabres** [comment] 2020-11-07 19:20
how can i fix this with code runner
[Running] python -u "c:\Users\Serban\classes.py"
<__main__.Dog object at 0x000002C32DBC7D00>

[Done] exited with code=0 in 0.169 seconds

**Comment by tbouchik** [comment] 2022-02-08 04:24
Updqting VSCode solved it for me

**Comment by YoanWai** [comment] 2022-06-01 22:50
> $HOME/Library/Application\ Support/Code

How do you get there??

**Comment by berty-b** [comment] 2022-10-10 12:11
> > $HOME/Library/Application\ Support/Code
> 
> How do you get there??

[Open your terminal](https://support.apple.com/en-gb/guide/terminal/apd5265185d-f365-44cb-8b09-71a064a42125/mac)

type the following into your terminal:

```
ll "$HOME"/Library/Application\ Support/Code/
```

Deleting the above folder did resolve/fix the issue for me, after I restarted/reloaded VS Code.

**Comment by balaji303** [comment] 2023-02-26 02:31
Just closing the app and opening it again solves the issue 👀
