### ISSUE TITLE
How i have to configure VS Code to don't get a “undefined reference” error message?

### ISSUE THREAD

**Issue by Pierre8r** [formulahendry/vscode-code-runner#376] opened 2018-10-05 13:53 UTC
My work environment :

EDI: Visual Studio Code

C ++ Compiler: GCC

Extensions:

Microsoft C / C ++

.run Code Runner

My source code :

main.cpp

    #include <iostream>
    #include "personne.h"
    
    int main() {
    
     personne jojo("fabien");
    
     std::cout <<"la personne s'appelle "<<jojo.get_nom()<<" et a " 
     <<jojo.get_age()<<" ans "<<std::endl;
    
     personne titi("lena",3);
    
     std::cout <<"la personne s'appelle "<<titi.get_nom()<<" et a " 
     <<titi.get_age()<<" ans "<<std::endl;
    }

personne.cpp

    #include "personne.h"
    
    std::string personne::get_nom() {
        return nom;
    }
    int personne::get_age() {
        return age;
    }
    
    personne::personne(std::string n){
        nom=n;
        age=0;
    }
    
    personne::personne(std::string n, int a) {
        nom=n;
        age=a;
    }

personne.h

    #ifndef __PERSONNE__
    #define __PERSONNE__
    
    #include <string>
    
    class personne {
        std::string nom;
        int age;enter code here
    
    public :
        std::string get_nom();
        int get_age();
    
        personne(std::string);
        personne(std::string, int);
    };
    
    #endif // __PERSONNE__

Errors messages :

> > Windows PowerShell Copyright (C) Microsoft Corporation. Tous droits réservés.
> 
> PS T:\VSCC++\LEssentiel> cd "t:\VSCC++\LEssentiel\chapitre 2  la
> programmation orientee objets\la_zim\" ; if ($?) { g++ main.cpp -o
> main } ; if ($?) { .\main }
> C:\Users\Pierre\AppData\Local\Temp\ccKhfKRw.o:main.cpp:(.text+0x4e):
> undefined reference to
> `personne::personne(std::__cxx11::basic_string<char,
> std::char_traits<char>, std::allocator<char> >)'
> C:\Users\Pierre\AppData\Local\Temp\ccKhfKRw.o:main.cpp:(.text+0x72):
> undefined reference to `personne::get_age()'
> C:\Users\Pierre\AppData\Local\Temp\ccKhfKRw.o:main.cpp:(.text+0x87):
> undefined reference to `personne::get_nom[abi:cxx11]()'
> C:\Users\Pierre\AppData\Local\Temp\ccKhfKRw.o:main.cpp:(.text+0x137):
> undefined reference to
> `personne::personne(std::__cxx11::basic_string<char,
> std::char_traits<char>, std::allocator<char> >, int)'
> C:\Users\Pierre\AppData\Local\Temp\ccKhfKRw.o:main.cpp:(.text+0x15b):
> undefined reference to `personne::get_age()'
> C:\Users\Pierre\AppData\Local\Temp\ccKhfKRw.o:main.cpp:(.text+0x170):
> undefined reference to `personne::get_nom[abi:cxx11]()' collect2.exe:
> error: ld returned 1 exit status PS T:\VSCC++\LEssentiel\chapitre 2 
> la programmation orientee objets\la_zim>

**Comment by babu-thomas** [comment] 2018-10-06 01:42
Hello @Pierre8r ,

The errors are due to `personne.cpp` not being compiled and linked with `main.cpp`. As far as I can tell, your current run command only compiles `main.cpp`. `main.cpp` includes the `personne.h` file but during linking `g++` can't find the definitions of the class functions because they are in `personne.cpp`.

To fix this change your run command for `cpp` in `code-runner.executorMap` to:
```
"code-runner.executorMap": {
        "cpp": "cd $dir && g++ -o $fileNameWithoutExt *.cpp && $dir$fileNameWithoutExt"
}
```
This command will compile and link all your `.cpp` files in the directory, and then run the compiled program.

If the above command doesn't work, then also attach your `settings.json` file in your comment so that I can better figure out what's going wrong.

**Comment by Pierre8r** [comment] 2018-10-10 08:57
Hello @babu-thomas ,
I think you're right.
But I do not have time to apply for the moment your advice.
As soon as I have time I apply your advice, and you give me some news.
Thank you.

**Comment by formulahendry** [comment] 2018-11-01 06:49
Thanks @babu-thomas !   Closing this now. @Pierre8r , Feel free to reopen or create new issue if you have question.

**Closed by formulahendry** 2018-11-01 06:49 UTC

**Comment by LAWRENCE-COPER** [comment] 2019-06-26 11:47
Thanks, @babu-thomas .I just came into this issue and with your method , the problem is well solved.

**Comment by Blossme233** [comment] 2019-12-02 18:06
It does not work on my vscode environment, get this error.
![image](https://user-images.githubusercontent.com/57247579/69983204-5db56980-14f3-11ea-9672-49593101f6e7.png)
![image](https://user-images.githubusercontent.com/57247579/69983261-7f165580-14f3-11ea-9ea8-03ebd3f1fecf.png)
Some wierd things happaned, when I tryed to inlude a .h file which I already defined, it will get errors, however, when I include the .cpp file which define members in the .h file, it works.
I guess the main.cpp does not link .o

**Comment by infinit-loop** [comment] 2020-12-11 05:02
Thanks @babu-thomas you saved my day.

**Comment by ANIKETMOHOD** [comment] 2021-03-28 20:27
Thanks Bro

**Comment by ibrahimballoul** [comment] 2022-04-01 00:15
Thanks @babu-thomas you  saved my dayyy

**Comment by niluse** [comment] 2022-04-28 10:40
thank you @babu-thomas. I really am was confused. :)
